### ISSUE TITLE
please update bitping

### ISSUE THREAD

**Issue by cecepabdul** [MRColorR/bitping#1]
docker run -it --mount type=volume,source="bitpingd-volume",target=/root/.bitpingd bitping/bitpingd:beta

**Comment by MRColorR** [comment]
Hello, please elaborate more :) 
This image should already be up to date with latest bitpingd app release

**Comment by cecepabdul** [comment]
![bitping](https://github.com/MRColorR/bitping/assets/34927384/6539ee8c-fa01-44fc-bd11-ffae2157b9b8)
![bitping1](https://github.com/MRColorR/bitping/assets/34927384/c1733aef-be52-4e25-966b-bb17126db822)
bitping upgrade to bitpingd https://hub.docker.com/r/bitping/bitpingd
